### ISSUE TITLE
Are Locators Required for GetAsync() Requests?

### ISSUE THREAD

**Issue by ilc-ilopez** [ISBronny/TeamCityAPI#1]
`await TeamCity.BuildTypes.GetAsync();`
Throws 
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
Because the Locator is missing in this type of request.
I need to enumerate my buildtypes/projects etc, and I noticed I couldnt (yet),
Using 0.1.0 at the moment.

**Comment by ISBronny** [comment]
Hey! Thanks for the issue. Fixed in 0.1.1.
**BuildTypes** does not require a locator. The use of locators is optional in most cases. But some models require a locator. For example, trying to get Test Occurrences `Client.TestOccurrences.GetAsync();` without locator will throw **ApiException**: _status code 400, unsupported test occurrence locator_
